# Site settings / Cấu hình trang
title: 'Safi Nguyễn'
description: 'Blog cá nhân của Nguyễn Hoàng Long'
keywords: 'art,gaming,technology'
url: 'https://SafiNguyen.github.io/' # your host
baseurl: ''

# nav / Thanh điều hướng
# Best experience: 6 tabs, each no more than 4 Chinese characters
nav:
  About: '/about.html' 
  Posts: '/'                # 首页
  Tags: '/tags.html'       # 标签
  Timeline: '/timeline.html' 
 # Friends: '/friendLink.html' 

# Author / Tác giả
author: true
name: 'Real name: Nguyễn Hoàng Long'
NickName: 'Nickname: Safi'
webtitle: 'Safi Nguyen'
bio: 'Information Technology Undergrad @ <a href="https://www.hcmus.edu.vn/" target="_blank">VNUHCM - HCMUS</a> • "we are our choices"'
about: true
aboutyou: 'I am a student at <a href="https://www.hcmus.edu.vn/" target="_blank">University of Science–VNUHCM</a>. I am interested in Game Development, Graphics Engineering, and Virtual Reality. At the same time, I’m still on the journey of exploring myself and shaping my own path in both learning and work. I’m eager to study and experience different aspects of coding and technology as a way to grow, improve, and eventually discover where my true passion lies. <br>Beyond academics, I enjoy reading, gaming and traveling. I am always eager to connect with like-minded individuals, discuss ideas, and collaborate on exciting projects and contests. Feel free to reach out if you would like to chat or work together!'
portraits: '/assets/profile.png' 

# SNS / Mạng xã hội
SNS: true
SNS-icon: # ['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:2512741165@student.hcmus.edu.vn'
  github: 'https://github.com/SafiNguyen'
  instagram: ''
  Twitter: ''
  Facebook: 'https://www.facebook.com/nguyen.hoang.long.166741'

# Pagination / Phân trang
paginate: 2
paginatepath: ['page:num']

# Footer / Chân trang
footer:
  since: 2025

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Code highlighting / Tô sáng cú pháp
highlighter: rouge
# Choose pygments theme: autumn, default, emacs, friendly, manni, murphy, pastie, perldoc, tango
pygmentsTheme: 'default'
# Seán. https://www.seanhalpin.xyz/
# Friends Links / Liên kết bạn bè
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# Comments / Bình luận
# Hãy chọn một hệ thống bình luận: facebook_comments, disqus, livere, gitment (ưu tiên theo thứ tự này)

# Facebook Comments
facebook_comments: false
facebook_app_id: ''
facebook_locale: 'vi_VN'
facebook_width: ''          # '' = auto 100% responsive
facebook_num_posts: 10
facebook_order_by: 'social' # time | reverse_time | social

# Disqus
disqus: true
# Preferred: set your shortname; we will build the embed URL from it
disqus_shortname: 'safinguyen'
# Optional: direct embed URL override (leave empty if using shortname)
disqus_url: '' # e.g. https://example.disqus.com/embed.js

# Livere
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # example code

# Gitment OAuth Application
Gitment: false
Gitment_owner: ''  # GitHub username
Gitment_repo: ''   # GitHub repo name
client_id: ''      # OAuth Application client_id
client_secret: ''  # OAuth Application client_secret

# Share buttons / Chia sẻ bài viết
# Options: weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['linkedin','twitter', 'facebook']

# Analytics / Thống kê
# Baidu Analytics - fill your code in baidu-url
baidu: false
baidu-url: ''
# Google Analytics - fill your tracking ID in google-ID
google: false
google-ID: ''

# Post header optional colors (used as page variables in post front matter)
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)