# Site settings / Cấu hình trang
title: 'Safi Nguyen'
description: 'Blog cá nhân của Nguyễn Hoàng Long'
keywords: 'art,gaming,technology'
url: 'https://SafiNguyen.github.io/' # your host
baseurl: ''

# nav / Thanh điều hướng
# Best experience: 6 tabs, each no more than 4 Chinese characters
nav:
  Home: '/'                # 首页
  Tags: '/tags.html'       # 标签
  Timeline: '/timeline.html' # 时间线
  About: '/about.html'     # 关于博主
  Friends: '/friendLink.html' # 友情链接

# Author / Tác giả
author: true
name: 'Nguyễn Hoàng Long'
NickName: 'Safi'
webtitle: 'Safi Nguyen'
bio: 'your awesome bio'
about: true
aboutyou: 'Tôi là một người yêu thích công nghệ và trò chơi điện tử.'
portraits: '/assets/profile.jpeg' # path to your portrait image

# SNS / Mạng xã hội
SNS: true
SNS-icon: # ['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:abc@gmail.com'
  weixin: '' # Đường dẫn ảnh QR WeChat của bạn
  qq: '' # Đường dẫn QR QQ hoặc link http://wpa.qq.com/msgrd?v=3&uin='yourQQ'&site=qq&menu=yes
  github: 'https://github.com/SafiNguyen'
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

# Pagination / Phân trang
paginate: 2
paginatepath: ['page:num']

# Footer / Chân trang
footer:
  since: 2018

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Code highlighting / Tô sáng cú pháp
highlighter: rouge
# Choose pygments theme: autumn, default, emacs, friendly, manni, murphy, pastie, perldoc, tango
pygmentsTheme: 'default'

# Friends Links / Liên kết bạn bè
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# Comments / Bình luận
# Best experience: choose one between disqus, livere, gitment
# Disqus
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# Livere
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # example code
# Gitment OAuth Application
Gitment: false
Gitment_owner: ''  # GitHub username
Gitment_repo: ''   # GitHub repo name
client_id: ''      # OAuth Application client_id
client_secret: ''  # OAuth Application client_secret

# Share buttons / Chia sẻ bài viết
# Options: weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['linkedin','twitter', 'facebook']

# Analytics / Thống kê
# Baidu Analytics - fill your code in baidu-url
baidu: false
baidu-url: ''
# Google Analytics - fill your tracking ID in google-ID
google: false
google-ID: ''

# Post header optional colors (used as page variables in post front matter)
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
